apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-api
  namespace: medical-dev
  labels:
    app: medical-api
spec:
  replicas: 2

  selector:
    matchLabels:
      app: medical-api

  template:
    metadata:
      labels:
        app: medical-api

    spec:
      containers:
        - name: medical-api
          image: medical-api:1.0.1
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 8000

          envFrom:
            - configMapRef:
                name: medical-api-config

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL