apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: {{ include "medical-api.fullname" . }}
  labels:
    {{- include "medical-api.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    blueGreen:
      activeService: {{ include "medical-api.fullname" . }}-active
      previewService: {{ include "medical-api.fullname" . }}-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30

  selector:
    matchLabels:
      {{- include "medical-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "medical-api.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: {{ .Chart.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ include "medical-api.fullname" . }}-config

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL